### ISSUE TITLE
The app doesn't work when I cloned and tried to run it

### ISSUE THREAD

**Issue by ngoquoc** [bl5ck/react-boilerplate-demo#1]
Initially, it can load the app successfully, where I can see the background image.
But few seconds later, the background disappears and a error stack trace shows up:

![image](https://user-images.githubusercontent.com/4502679/41200310-87eb2756-6ccc-11e8-81b7-5ae438b8acaa.png)

**Comment by bl5ck** [comment]
That was because of circular import statements:
`utils/index` -> `utils/apiUtils` -> `mockData/apiData` -> `utils/index`.

Fixed it by importing exact `stringUtils`.
